spring.application.name=settleFlow

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/settleflow_db
spring.datasource.username=settle_user
spring.datasource.password=settle_pass123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=secret
jwt.expiration=86400
jwt.refresh-expiration=604800